### ISSUE TITLE
error about .coords

### ISSUE THREAD

**Issue by hemomona** [cbmi-group/DeepETPicker#3]
Hi, 

I used deepetpicker to manually pick just one class of particles, 30 in one reconstruction and 9 in the other. I went well in the preprocess, however, after I click "train", error pops up.

![image](https://github.com/cbmi-group/DeepETPicker/assets/50448982/8bab2f89-3e19-4f79-882b-b38af5c01a43)

The reconstruction is bin4 and denoised by IsoNet, I wonder why this error is happened and how to fix it.
PS: In the imod, I did not choose to "covert to bytes" in the postprocess, is that the problem?

**Comment by hemomona** [comment]
![image](https://github.com/cbmi-group/DeepETPicker/assets/50448982/5b3a9af0-44ad-48eb-add2-86a8cc86cbbd)

**Comment by lgl603** [comment]
I did not encounter this error ever. I can not find a solution based on the information you provided. Could you please copy a complete error message?  

Or if your data is not too large, could you give me a sample data through email (guole.liu@ia.ac.cn)?

**Comment by hemomona** [comment]
Hi, I'm sorry that I can not repeat the problem now. But at that time I encountered an ValueError problem as well, even if I used the sample data of SHREC_2021.

The model_0.mrc, model_0.coords, model_1.mrc, and model_1.coords are in the SHREC_2021 you supplied, and the following is the log. I appreciate your reply and kindness.

Load training configs: /data/Huwanlong/deepetpicker-test/configs/train.py
****************************************************************************************************
dset_name: train
base_path: /data/Huwanlong/deepetpicker-test
coord_path: /data/Huwanlong/deepetpicker-test/coords
coord_format: .coords
tomo_path: /data/Huwanlong/deepetpicker-test/data_std
tomo_format: .mrc
num_cls: 1
label_name: 5
label_path: /data/Huwanlong/deepetpicker-test/5
label_type: 
label_diameter: 5
ocp_type: sphere
ocp_diameter: 9
ocp_name: data_ocp
ocp_path: /data/Huwanlong/deepetpicker-test/data_ocp
norm_type: standardization
model_name: ResUNet
train_set_ids: 0
val_set_ids: 1
batch_size: 16
patch_size: 72
padding_size: 12
lr: 0.0005
max_epochs: 60
seg_thresh: 0.5
gpu_ids: 0
****************************************************************************************************
save train configs to '/data/Huwanlong/deepetpicker-test/configs/train.py'
Load training configs: /data/Huwanlong/deepetpicker-test/configs/train.py
****************************************************************************************************
dset_name: train
base_path: /data/Huwanlong/deepetpicker-test
coord_path: /data/Huwanlong/deepetpicker-test/coords
coord_format: .coords
tomo_path: /data/Huwanlong/deepetpicker-test/data_std
tomo_format: .mrc
num_cls: 1
label_name: 5
label_path: /data/Huwanlong/deepetpicker-test/5
label_type: 
label_diameter: 5
ocp_type: sphere
ocp_diameter: 9
ocp_name: data_ocp
ocp_path: /data/Huwanlong/deepetpicker-test/data_ocp
norm_type: standardization
model_name: ResUNet
train_set_ids: 0
val_set_ids: 1
batch_size: 16
patch_size: 72
padding_size: 12
lr: 0.0005
max_epochs: 60
seg_thresh: 0.5
gpu_ids: 0
****************************************************************************************************
****************************************************************************************************
Final training configuration parameters
****************************************************************************************************
Training dataset Name: train
Training model name: ResUNet
Number of training classes: 1
Training - batch size: 16
Training -  patch size: 72
Training -  padding size: 12
Training - max epochs: 60
Training - segmentation threshold: 0.5
Training - gpu ids: 0
****************************************************************************************************
val_first:1
data_split:[0, 1, 1, 2, 1, 2]
12
ResidualUNet3D(
  (pools): ModuleList(
    (0): AvgPool3d(kernel_size=2, stride=2, padding=0)
    (1): AvgPool3d(kernel_size=2, stride=2, padding=0)
    (2): AvgPool3d(kernel_size=2, stride=2, padding=0)
  )
  (encoders): ModuleList(
    (0): Encoder(
      (basic_module): ExtResNetBlock(
        (conv1): SingleConv(
          (conv): Conv3d(4, 24, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1))
          (batchnorm): BatchNorm3d(24, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU()
        )
        (conv2): SingleConv(
          (conv): Conv3d(24, 24, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1))
          (batchnorm): BatchNorm3d(24, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU()
        )
        (conv3): SingleConv(
          (conv): Conv3d(24, 24, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1))
          (batchnorm): BatchNorm3d(24, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU()
        )
        (non_linearity): ELU(alpha=1.0, inplace=True)
      )
      (coord_conv): AddCoords()
    )
    (1): Encoder(
      (pooling): AvgPool3d(kernel_size=2, stride=2, padding=0)
      (basic_module): ExtResNetBlock(
        (conv1): SingleConv(
          (conv): Conv3d(28, 48, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1))
          (batchnorm): BatchNorm3d(48, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU()
        )
        (conv2): SingleConv(
          (conv): Conv3d(48, 48, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1))
          (batchnorm): BatchNorm3d(48, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU()
        )
        (conv3): SingleConv(
          (conv): Conv3d(48, 48, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1))
          (batchnorm): BatchNorm3d(48, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU()
        )
        (non_linearity): ELU(alpha=1.0, inplace=True)
      )
      (coord_conv): AddCoords()
    )
    (2): Encoder(
      (pooling): AvgPool3d(kernel_size=2, stride=2, padding=0)
      (basic_module): ExtResNetBlock(
        (conv1): SingleConv(
          (conv): Conv3d(52, 72, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1))
          (batchnorm): BatchNorm3d(72, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU()
        )
        (conv2): SingleConv(
          (conv): Conv3d(72, 72, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1))
          (batchnorm): BatchNorm3d(72, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU()
        )
        (conv3): SingleConv(
          (conv): Conv3d(72, 72, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1))
          (batchnorm): BatchNorm3d(72, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU()
        )
        (non_linearity): ELU(alpha=1.0, inplace=True)
      )
      (coord_conv): AddCoords()
    )
    (3): Encoder(
      (pooling): AvgPool3d(kernel_size=2, stride=2, padding=0)
      (basic_module): ExtResNetBlock(
        (conv1): SingleConv(
          (conv): Conv3d(76, 108, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1))
          (batchnorm): BatchNorm3d(108, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU()
        )
        (conv2): SingleConv(
          (conv): Conv3d(108, 108, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1))
          (batchnorm): BatchNorm3d(108, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU()
        )
        (conv3): SingleConv(
          (conv): Conv3d(108, 108, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1))
          (batchnorm): BatchNorm3d(108, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU()
        )
        (non_linearity): ELU(alpha=1.0, inplace=True)
      )
      (coord_conv): AddCoords()
    )
  )
  (decoders): ModuleList(
    (0): Decoder(
      (coord_conv): AddCoords()
      (upsampling): Upsampling(
        (upsample): ConvTranspose3d(108, 72, kernel_size=(3, 3, 3), stride=(2, 2, 2), padding=(1, 1, 1))
      )
      (basic_module): ExtResNetBlock(
        (conv1): SingleConv(
          (conv): Conv3d(75, 72, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1))
          (batchnorm): BatchNorm3d(72, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU()
        )
        (conv2): SingleConv(
          (conv): Conv3d(72, 72, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1))
          (batchnorm): BatchNorm3d(72, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU()
        )
        (conv3): SingleConv(
          (conv): Conv3d(72, 72, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1))
          (batchnorm): BatchNorm3d(72, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU()
        )
        (non_linearity): ELU(alpha=1.0, inplace=True)
      )
    )
    (1): Decoder(
      (coord_conv): AddCoords()
      (upsampling): Upsampling(
        (upsample): ConvTranspose3d(72, 48, kernel_size=(3, 3, 3), stride=(2, 2, 2), padding=(1, 1, 1))
      )
      (basic_module): ExtResNetBlock(
        (conv1): SingleConv(
          (conv): Conv3d(51, 48, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1))
          (batchnorm): BatchNorm3d(48, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU()
        )
        (conv2): SingleConv(
          (conv): Conv3d(48, 48, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1))
          (batchnorm): BatchNorm3d(48, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU()
        )
        (conv3): SingleConv(
          (conv): Conv3d(48, 48, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1))
          (batchnorm): BatchNorm3d(48, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU()
        )
        (non_linearity): ELU(alpha=1.0, inplace=True)
      )
    )
    (2): Decoder(
      (coord_conv): AddCoords()
      (upsampling): Upsampling(
        (upsample): ConvTranspose3d(48, 24, kernel_size=(3, 3, 3), stride=(2, 2, 2), padding=(1, 1, 1))
      )
      (basic_module): ExtResNetBlock(
        (conv1): SingleConv(
          (conv): Conv3d(27, 24, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1))
          (batchnorm): BatchNorm3d(24, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU()
        )
        (conv2): SingleConv(
          (conv): Conv3d(24, 24, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1))
          (batchnorm): BatchNorm3d(24, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU()
        )
        (conv3): SingleConv(
          (conv): Conv3d(24, 24, kernel_size=(3, 3, 3), stride=(1, 1, 1), padding=(1, 1, 1))
          (batchnorm): BatchNorm3d(24, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU()
        )
        (non_linearity): ELU(alpha=1.0, inplace=True)
      )
    )
  )
  (final_conv): Conv3d(24, 1, kernel_size=(1, 1, 1), stride=(1, 1, 1))
)
****************************************************************************************************
num_name:
/data/Huwanlong/deepetpicker-test/coords/num_name.csv
base_path:/data/Huwanlong/deepetpicker-test
coord_path:/data/Huwanlong/deepetpicker-test/coords
tomo_path:/data/Huwanlong/deepetpicker-test/data_std
label_path:/data/Huwanlong/deepetpicker-test/5
ocp_path:/data/Huwanlong/deepetpicker-test/data_ocp
label_name:5
coord_format:.coords
tomo_format:.mrc
norm_type:standardization
ocp_name:data_ocp
****************************************************************************************************
        0        1  2
0  1395.0  model_0  0
1  2073.0  model_1  1
36
48
Test dataset contains 605 samples
/data/Huwanlong/deepetpicker-test/data_ocp/model_1.mrc

Validation sanity check: 0it [00:00, ?it/s]

Validation sanity check:  50%|#####     | 1/2 [00:00<00:00,  2.19it/s]

Validation sanity check: 100%|##########| 2/2 [00:00<00:00,  2.71it/s]
Exception in thread 
Thread-17
:

Traceback (most recent call last):

  File "/home/spuser/.conda/envs/deepetpicker/lib/python3.8/threading.py", line 932, in _bootstrap_inner

    
self.run()
  File "/home/spuser/.conda/envs/deepetpicker/lib/python3.8/threading.py", line 870, in run

    
self._target(*self._args, **self._kwargs)
  File "/data/Huwanlong/DeepETPicker/train.py", line 364, in train_func

    
runner.fit(model)
  File "/home/spuser/.conda/envs/deepetpicker/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 470, in fit

    
results = self.accelerator_backend.train()
  File "/home/spuser/.conda/envs/deepetpicker/lib/python3.8/site-packages/pytorch_lightning/accelerators/dp_accelerator.py", line 110, in train

    
results = self.train_or_test()
  File "/home/spuser/.conda/envs/deepetpicker/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 65, in train_or_test

    
results = self.trainer.train()
  File "/home/spuser/.conda/envs/deepetpicker/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 492, in train

    
self.run_sanity_check(self.get_model())
  File "/home/spuser/.conda/envs/deepetpicker/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 690, in run_sanity_check

    
_, eval_results = self.run_evaluation(test_mode=False, max_batches=self.num_sanity_val_batches)
  File "/home/spuser/.conda/envs/deepetpicker/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 622, in run_evaluation

    
deprecated_eval_results = self.evaluation_loop.evaluation_epoch_end()
  File "/home/spuser/.conda/envs/deepetpicker/lib/python3.8/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 208, in evaluation_epoch_end

    
deprecated_results = self.__run_eval_epoch_end(self.num_dataloaders, using_eval_result)
  File "/home/spuser/.conda/envs/deepetpicker/lib/python3.8/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 246, in __run_eval_epoch_end

    
eval_results = model.validation_epoch_end(eval_results)
  File "/data/Huwanlong/DeepETPicker/train.py", line 177, in validation_epoch_end

    
cal_metrics_NMS_OneCls(coords_out,
  File "/data/Huwanlong/DeepETPicker/utils/misc.py", line 179, in cal_metrics_NMS_OneCls

    
x, y, z = gt_coords[i]
ValueError
: 
too many values to unpack (expected 3)

**Comment by lgl603** [comment]
Hello !
SHREC2021 is a sample dataset for multi-class particle picking. The detailed tutorial could be accessed by https://github.com/cbmi-group/DeepETPicker/blob/main/tutorials/A_tutorial_of_particlePicking_on_SHREC2021_dataset.md.

There are different format of the .coords file for multi-class and single-class particle picking. So the configs for the steps of `Preprocessing` and `Training` are slightly different, including the `Numer of classes` and `Ocp diameter` in the `Preprocessing` step and `Number of classes` in the `Training` step.

<img width="688" alt="image" src="https://github.com/cbmi-group/DeepETPicker/assets/16335327/3554a1e6-d8ca-4e44-88f4-a3e7ae3d5a78">

<img width="663" alt="image" src="https://github.com/cbmi-group/DeepETPicker/assets/16335327/f59d3626-2230-408b-a2f3-ae7538aa84de">

Therefore, the reason for 'error about .coords' is that the `Numer of classes` in the `Training` panel should be set as 14 for SHREC2021 instead of 1.

**Comment by hemomona** [comment]
Thank for your reply.

I finally used your "particle visualization" function to manually picked around 50 tomograms. However, this time I get around 500 tomograms, seems that I have to try your automatic pick in my dataset...

but there is always a "Label Generation Exception" in the preprocess step. I don't know why there is a ocp diameter besides label diameter and I don't how smaller the label diameter should be compared to the ocp diameter and my particle diameter either. Could you please explain that for me. Thank you very much.

PS: I tried many combinations of label diameter and ocp diameter, like 50 50, 25 50, and 24 50. when using 50 50, there is a "label generation Exception! Label Generation Error!" when using the latter two, there is a " label generation finished! Label Generation Error!" I'm totally confused.
![屏幕截图 2023-03-07 120401](https://github.com/cbmi-group/DeepETPicker/assets/50448982/6bf8f6c6-4b75-4feb-abb6-3e7ea0cefc5c)

**Comment by lgl603** [comment]
The `ocp diameter` denotes the real diameter of the particles. Empirically, in order to obtain good selection results, we recommend that the particle size is adjusted to the range of 20~30 by binning operation.

The `label diameter` denotes the diameter of generated weak label, which is usually smaller than the average diameter of the particles. Empirically, you can set it as large as possible but should be smaller than the real diameter.

As for your case, you can bin your tomogram using a factor of 2. Thus, the particle diameter is around 25. The combinations of label diameter and ocp diameter could be 15, 25.

**Comment by hemomona** [comment]
thanks a lot, it works.
