### ISSUE TITLE
empty results generated

### ISSUE THREAD

**Issue by pratyush-1** [cbmi-group/DeepETPicker#4]
Hi,
Upon executing all the commands given in bin/bash_command.md. I get empty results.

I made path changes in the configs/SHREC_2021_preprocess.py

```
pre_config={"dset_name": "SHREC_2021_preprocess",
            "base_path": "/home/pratyush/Desktop/DeepETPicker",
            "coord_path": "/home/pratyush/Desktop/DeepETPicker/raw_data",
            "coord_format": ".coords",
            "tomo_path": "/home/pratyush/Desktop/DeepETPicker/raw_data",
            "tomo_format": ".mrc",
            "num_cls": 14,
            "label_type": "gaussian",
            "label_diameter": 9,
            "ocp_type": "sphere",
            "ocp_diameter": "7,7,7,7,7,9,9,9,11,11,13,13,13,17",
            "norm_type": "standardization"}
```
the training takes place properly
```
python test_bash.py \
--train_configs 'Train_Config_Name' \
--checkpoints 'Checkpoint_Path'
```
Executing above test code first gives the following error - 
`FileNotFoundError: /home/pratyush/Desktop/DeepETPicker/data_std/num_name.csv not found.`
To tackle above issue, I copy the num_name.csv from coords folder generated to data_std folder.

Again I run the testing script and after executing , it gives results as follows - 
```
        0        1  2
0  1395.0  model_0  0
1  2073.0  model_1  1
2  2199.0  model_2  2
3  2905.0  model_3  3
4  2155.0  model_4  4
5  1877.0  model_5  5
6  1915.0  model_6  6
7  1186.0  model_7  7
8  1461.0  model_8  8
data_range:[8]
36 48
Test dataset contains 605 samples
Testing: 100%|████████████████████████████████| 152/152 [00:45<00:00,  3.40it/s]coords_out: (29996, 5)
de_duplication
Before De_Dup: 29996
After De_Dup: 1746
Testing: 100%|████████████████████████████████| 152/152 [01:00<00:00,  2.50it/s]
--------------------------------------------------------------------------------
DATALOADER:0 TEST RESULTS
{}
--------------------------------------------------------------------------------
****************************************************************************************************
Testing Finished!
****************************************************************************************************
```
The results folder generated is empty.  Could you tell why the results generated are empty?

Thank you

**Comment by lgl603** [comment]
We have updated our code to solve the error "FileNotFoundError: /home/pratyush/Desktop/DeepETPicker/data_std/num_name.csv not found.". You can update your code by the command "git clone https://github.com/cbmi-group/DeepETPicker.git"

The pretrained checkpoints and predicted coordinates are saved in the sub-folder `runs` of `base_path`.

An examplet of folder structure is as follows:

<img width="406" alt="20240520163736" src="https://github.com/cbmi-group/DeepETPicker/assets/16335327/9530f51d-060e-4c82-937a-88505ff3c829">
