### ISSUE TITLE
how to download tutorial data

### ISSUE THREAD

**Issue by EricDeveaud** [cbmi-group/DeepETPicker#9]
Hello

Microsoft OneDrive links gives permission denied. 
baidu link can't deal with chinese language....

can you explain how to download tutorial data.

regards

Eric

**Comment by lgl603** [comment]
> Hello
> 
> Microsoft OneDrive links gives permission denied. baidu link can't deal with chinese language....
> 
> can you explain how to download tutorial data.
> 
> regards
> 
> Eric

We have provided sample data through zenodo, and you can download it through the link https://zenodo.org/records/12512436.

**Comment by EricDeveaud** [comment]
thanks
Eric
